# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_as_csv_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 170)
        Dialog.setMinimumSize(QtCore.QSize(400, 170))
        Dialog.setMaximumSize(QtCore.QSize(400, 170))
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 22, 383, 139))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditExportTimeRange = QtWidgets.QLineEdit(self.widget)
        self.lineEditExportTimeRange.setMinimumSize(QtCore.QSize(108, 25))
        self.lineEditExportTimeRange.setMaximumSize(QtCore.QSize(108, 25))
        self.lineEditExportTimeRange.setSizeIncrement(QtCore.QSize(108, 25))
        self.lineEditExportTimeRange.setObjectName("lineEditExportTimeRange")
        self.horizontalLayout_2.addWidget(self.lineEditExportTimeRange)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditFileName = QtWidgets.QLineEdit(self.widget)
        self.lineEditFileName.setMinimumSize(QtCore.QSize(381, 25))
        self.lineEditFileName.setMaximumSize(QtCore.QSize(381, 25))
        self.lineEditFileName.setObjectName("lineEditFileName")
        self.verticalLayout.addWidget(self.lineEditFileName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonOk = QtWidgets.QPushButton(self.widget)
        self.pushButtonOk.setObjectName("pushButtonOk")
        self.horizontalLayout.addWidget(self.pushButtonOk)
        self.pushButtonCancel = QtWidgets.QPushButton(self.widget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Rango de tiempo:"))
        self.label_2.setText(_translate("Dialog", "Nombre:"))
        self.pushButtonOk.setText(_translate("Dialog", "OK"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancelar"))
